### ISSUE TITLE
Erro ao baixar os arquivos

### ISSUE THREAD

**Issue by canzone** [gustavosf/api.legendas.tv#4]
Oi Gustavo,

Primeiro, muito obrigado pelo projeto. Sua solução funciona perfeitamente, é elegante e limpa.

Uso já tem bastante tempo mas, há coisa de uns dias, começou a dar erro. Eu acho que o pessoal do site mudou a distribuição de alguma página. O erro é esse:

PHP Warning:  file_put_contents(): Filename cannot be empty in ../lib/legendastv.php on line 209

Tentei ver o conteúdo das variáveis e traz um longo script, mais uma evidência de que mudaram algo no site. Mas meu mísero conhecimento de PHP morre por aí (sou das linguagens antigas, já mortas, hehe).

Se você ainda estiver mantendo o projeto, fica aí o comentário. Eu vou continuar fuçando, mas PHP realmente não é minha praia.

Obrigado!

**Comment by gustavosf** [comment]
Opa, tudo bem?
Vou dar uma checada. Eu uso o script aqui também pra baixar legendas então assim que eu ajeitar eu mando um fix e te aviso :)

Valeu!

**Comment by gustavosf** [comment]
Lancei um fix bem simples no commit acima ^ que deve resolver o problema :)

**Comment by canzone** [comment]
Oi Gustavo,

Muito obrigado por olhar o problema tão rápido!

Baixei a versão nova mas infelizmente continua dando o mesmo erro, embora em uma linha diferente:
PHP Warning:  file_put_contents(): Filename cannot be empty in ./lib/legendastv.php on line 231

Obrigado de novo.

**Comment by canzone** [comment]
Olá Gustavo,

Descobri o problema, caso te interesse em atacar a questão. Eu criei uma conta VIP no Legendas.tv (para contribuir com o pessoal) e o problema começou a acontecer. Agora fiz um teste com a conta de um amigo, que não é VIP, e funcionou normalmente.

Mais uma vez, muito obrigado.
